name = "kokic/uml-live"

version = "0.1.0"

import {
  "moonbit-community/rabbita@0.15.6",
  "kokic/uml@0.2.4",
  "Yoorkin/rui@0.1.2",
}

readme = "README.md"

repository = ""

license = "Apache-2.0"

keywords = [ ]

description = "A Rabbita app generated by Warren."

preferred_target = "js"
